#!/bin/bash

# Installation: Add this script in your path (or create a link in your path)
# Pre-requesite:
#   `brew install sshuttle`
#   export APP_INTERFACE_DIR=<path-to-your-app-interface-clone> # default = $HOME/dev/service/app-interface
# Nice to have (avoids having to enter your password):
#   shuttle --sudoers
#   sudo sh -c "echo '$USER ALL=NOPASSWD: /sbin/route' >> /private/etc/sudoers.d/sshuttle_auto"
# Usage: cluster-proxy
# What it does:
#   - find all hive cluster CIDRs from app-interface
#   - due to issue https://github.com/sshuttle/sshuttle/issues/538, add route to hive cidrs via ens0
#   - run sshuttle for all hive cluster CIDRs
#   - cleanup routes on SIGINT (CTRL-C) to stop sshuttle

# From Maor
# get_hive_cidrs(){
#   #echo "$(curl -s -H "Authorization: Basic REDACTED" -g "https://app-interface.devshift.net/graphql?query={namespaces:namespaces_v1{name,cluster{network{vpc}}}}" | jq -r '.data.namespaces[] | select(.name=="hive") | .cluster.network.vpc' | tr '\n' ' ')"
# }
# alias ssh-hive='(set -x ; sshuttle -r bastion.ci.ext.devshift.net $(get_hive_cidrs))'

# CLUSTER_PROXY_CIDRS=$(grep '^  vpc:' "${APP_INTERFACE_DIR:-$HOME/dev/service/app-interface}"/data/openshift/hive*/cluster.yml | awk '{print $3}' | tr '\n' ' ')
# CLUSTER_PROXY_CIDRS="10.0.0.0/8"
BACKPLANE_CIDR="10.170.0.0/16"  # this is actually split in multiple cidr blocks
#backplanes03ue1: 10.170.28.0/22
CLUSTER_PROXY_CIDRS="10.125.0.0/16 10.163.0.0/16 10.133.0.0/16 10.162.0.0/16 10.134.0.0/16 10.124.0.0/16 10.123.0.0/16 10.164.0.0/16 10.135.0.0/16 10.132.0.0/16 10.136.0.0/16 $BACKPLANE_CIDR"

# https://github.com/sshuttle/sshuttle/issues/538
_cluster_proxy_route_cleanup() {
  echo "CLEANUP !"
  for cidr in ${CLUSTER_PROXY_CIDRS} ; do
    set -x
    sudo route delete -net "$cidr" -interface en0
    set +x
  done
}

trap _cluster_proxy_route_cleanup INT

for cidr in ${CLUSTER_PROXY_CIDRS} ; do
  set -x
  sudo route add -net "$cidr" -interface en0
  set +x
done

echo "Proxying $CLUSTER_PROXY_CIDRS ..."
# --dns
set -x
sshuttle -r bastion.ci.int.devshift.net ${CLUSTER_PROXY_CIDRS}
set +x
#bastion.ci.ext.devshift.net
# bash -c "$(qontract-cli --config ~/dev/app-sre/qontract-reconcile/config.prod.toml get sshuttle-command bastion.ci.int.devshift.net)"
# ---> sshuttle -r bastion.ci.ext.devshift.net 10.164.0.0/16 10.135.0.0/16 10.132.0.0/16 10.136.0.0/16 10.202.0.0/16 10.134.0.0/16 10.163.0.0/16 10.133.0.0/16 10.125.0.0/16 10.124.0.0/16 10.123.0.0/16 10.162.0.0/16
