#!/bin/bash

# Usage: source this file from your ~/.bash-profile

# Parse app-interface to retrieve cluster information in $HOME/.ocl files with 'oclgen'.
#   Just run 'oclgen'. It will parse files from ${APP_INTERFACE_DIR} or $HOME/src/app-interface by default
# 
# Automate openshift login against cluster info retrieved with oclgen and set of some shell variable with 'ocl'.
#   The following variables will be set:
#   * OCL_CLUSTER_NAME
#   * OCL_API_URL
#   * OCL_CONSOLE_URL
#   * OCL_DOMAIN
#   * OCL_APPS_URL_SUFFIX
#   If the current token is not valid anymore, the login web page will be opened to let you copy and paste it on the command line prompt.
# Auto-complete cluster names on 'ocl' invocations, based on 'oclgen' gathered info.
# 
# Call the '_ocl_ps1' function to print currently logged in cluster information. Can be used in a PROMPT_COMMAND line.
#   eg: PROMPT_COMMAND='__git_ps1 "\n⭕️ $(_ocl_ps1)\nlocal:\w" " \$ "'
# 
# Logout with 'oclo' to logout and unset OCL_* shell variables.

ocl() {
    if [ -z "${1}" ] ; then
        if [ -n "${OCL_CLUSTER_NAME}" ] ; then
            echo "Currently configured to access cluster ${OCL_CLUSTER_NAME}"
        else
            echo "Missing param: cluster_name."
        fi
        echo "Known clusters:"
        echo
        ls -1 "$HOME/.ocl"
        exit 1
    fi

    if [ ! -f "$HOME/.ocl/$1" ] ; then
        echo "File not found $HOME/.ocl/$1"
        echo "Missign cluster $1 definition"
        exit 1
    fi

    # unset all variables starting with OCL_
    unset ${!OCL_*}
    # unset $(set | grep "^OCL_" | cut -f1 -d=)
    # unset OCL_API_URL
    # unset OCL_APPS_URL_SUFFIX
    # unset OCL_CONSOLE_URL

    source "${HOME}/.ocl/${1}"

    : "${OCL_API_URL:=https://api.${OCL_DOMAIN}:6443}"
    : "${OCL_APPS_URL_SUFFIX:=apps.${OCL_DOMAIN}}"
    : "${OCL_CONSOLE_URL:=https://console-openshift-console.${OCL_APPS_URL_SUFFIX}}"

    export KUBECONFIG="${HOME}/.kube/config_${OCL_CLUSTER_NAME}"

    if [ -f "${KUBECONFIG}" ] && oc whoami ; then
        echo "Already logged in"
    else
        open https://oauth-openshift.${OCL_APPS_URL_SUFFIX}/oauth/token/request
        echo "Please login on the open web window copy the generated token here"
        read -r TOKEN
        if [ -n "${TOKEN}" ] ; then
            (set -e ; oc login "${OCL_API_URL}" --token "${TOKEN}")
        else
            echo "Empty token, skipping login"
        fi
    fi

    # OCL_PS1="${COLOR_GRAY}${OCL_CLUSTER_NAME} (Console: ${OCL_CONSOLE_URL})${COLOR_DEFAULT}"

    echo "Cluster: ${OCL_CLUSTER_NAME}"
    echo "API URL: ${OCL_API_URL}"
    echo "Console: ${OCL_CONSOLE_URL}"
}

oclo() {
    oc logout
    unset ${!OCL_*} KUBECONFIG
}

_ocl_ps1() {
    if [ -n "$OCL_CLUSTER_NAME" ] ; then
        echo "${COLOR_GRAY}${OCL_CLUSTER_NAME} / $(kubens --current) (Console: ${OCL_CONSOLE_URL})${COLOR_DEFAULT}"
    else
        #echo "${COLOR_GRAY}N/A${COLOR_DEFAULT}"
	echo
    fi
}

oclgen() {
    local clustername api_url domain
    local app_interface="${APP_INTERFACE_DIR:-$HOME/src/app-interface}"
    for f in $(grep -lR '^$schema: /openshift/cluster-1.yml' ${app_interface} | grep -E 'ya?ml') ; do
        clustername=$(grep '^name:' "$f" | cut -f2 -d' ')
        echo "Parsing $f into $HOME/.ocl/$clustername"
        api_url=$(grep '^serverUrl:' "$f" | cut -f2 -d' ')
        domain=$(echo "${api_url:12}" | cut -f1 -d:)
        {
            echo 'OCL_CLUSTER_NAME=$(basename "${BASH_SOURCE}")'
            echo "OCL_DOMAIN=$domain"
            echo "OCL_API_URL=${api_url}"
            echo "OCL_CONSOLE_URL=$(grep '^consoleUrl:' "$f" | cut -f2 -d' ')"
        } > "$HOME/.ocl/$clustername"
    done
}

# stollen from https://devmanual.gentoo.org/tasks-reference/completion/index.html
_ocl() {
	local cur opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	opts=$(ls -1 "$HOME/.ocl")
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}
complete -F _ocl ocl
